[tool.poetry]
name = "diplom10"
version = "0.1.0"
description = ""
authors = ["aleyakh <aleyakh@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
